"""
CarTrust Phase 3 Schemas

Pydantic models for all Phase 3 outputs: flags, dimension assessments,
contradictions, cost estimates, and the final TrustReport.
"""

from typing import List, Literal, Optional

from pydantic import BaseModel, Field


class Flag(BaseModel):
    """A specific, actionable issue identified by the rule engine."""

    flag_id: str = Field(
        description="Stable identifier: ODO_MULTI_SIGNAL_DISCREPANCY, FIN_UNDISCLOSED_LOAN"
    )
    severity: Literal["low", "medium", "high", "critical"] = Field(
        description="Determined by the rule engine, never by the LLM."
    )
    evidence_summary: str = Field(
        description="Technical summary generated by the rule engine."
    )
    suggested_actions: List[str] = Field(
        default_factory=list,
        description="Specific actions for the buyer. Generated by the rule engine."
    )
    description: str = Field(
        default="",
        description="Plain-language explanation for Rahul. Filled by LLM explanation layer."
    )


class DimensionAssessment(BaseModel):
    """The rule engine's judgment about one dimension, with LLM-generated explanation text."""

    dimension: str = Field(description="ownership, odometer, accident, financial, service")
    state: Literal[
        "verified_clean", "verified_flagged", "unverifiable",
        "active_resolvable", "critical"
    ] = Field(description="Determined by rule engine.")
    flags: List[Flag] = Field(default_factory=list)
    score: float = Field(ge=0.0, le=1.0, description="Computed by rule engine.")
    summary: str = Field(default="", description="One-sentence summary. Filled by LLM.")
    reasoning: str = Field(default="", description="Detailed reasoning. Filled by LLM.")


class Contradiction(BaseModel):
    """A conflict between evidence from different dimensions."""

    contradiction_id: str
    dimensions_involved: List[str]
    severity: Literal["low", "medium", "high", "critical"]
    evidence_summary: str = Field(description="Technical summary. Rule engine generated.")
    description: str = Field(default="", description="Plain-language explanation. LLM generated.")


class CostEstimate(BaseModel):
    """Projected 3-year ownership cost. LLM + RAG generated."""

    annual_maintenance_low: int
    annual_maintenance_high: int
    annual_insurance_estimate: int
    total_3yr_low: int
    total_3yr_high: int
    fair_market_value_low: int
    fair_market_value_high: int
    basis: str = Field(description="What knowledge source was used.")


class TrustReport(BaseModel):
    """Complete Phase 3 output. Rendered by Phase 4 Streamlit app and PDF generator."""

    registration_number: str = ""
    make: str
    model: str
    year: int
    listing_price: Optional[int] = None

    assessments: List[DimensionAssessment] = Field(default_factory=list)
    contradictions: List[Contradiction] = Field(default_factory=list)

    composite_score: float = Field(ge=0.0, le=1.0)
    coverage_ratio: float = Field(ge=0.0, le=1.0)
    confidence_level: Literal["high", "moderate", "low"]

    verdict: Literal["BUY", "NEGOTIATE", "NEGOTIATE_WITH_SAFEGUARDS", "WALK_AWAY"]
    verdict_explanation: str = ""

    action_checklist: List[str] = Field(default_factory=list)
    cost_estimate: Optional[CostEstimate] = None
    unverifiable_dimensions: List[str] = Field(default_factory=list)
    unverifiable_explanation: str = ""
