"use client";

import { useState } from "react";

const faqs = [
  {
    q: "Does CarTrust access RTO/Parivahan databases directly?",
    a: "CarTrust works with the data you provide — RC document photos, service logs, insurance records, and seller disclosures. It cross-references these for consistency and flags contradictions. Direct RTO integration requires regulatory approval we are pursuing.",
  },
  {
    q: "Is the BUY/WALK AWAY verdict generated by AI?",
    a: "No. The verdict is produced by a deterministic rule engine — fixed logical rules, not AI. The AI's only role is to explain the rule engine's findings in plain language. This means verdicts are consistent, reproducible, and explainable.",
  },
  {
    q: "What is a 'hard stop' and why does it override everything?",
    a: "A hard stop is triggered when a critical issue is found — like an active bank loan on the vehicle. No matter how good the rest of the assessment is, you cannot legally transfer ownership of such a car. The composite score becomes 0 and the verdict is WALK AWAY.",
  },
  {
    q: "How accurate is the odometer rollback detection?",
    a: "We compare the stated odometer against service log dates/items, age-adjusted industry norms, and stated mileage from multiple sources. A discrepancy above 10% triggers a flag. It's not infallible without hardware inspection, but it catches the most common rollback patterns.",
  },
  {
    q: "Is my data stored or shared?",
    a: "Assessment data is processed in memory and not stored in any database. The car details you enter are used only to generate your report and are discarded after the session ends.",
  },
  {
    q: "Can I download the report?",
    a: "Yes. Every completed assessment generates a downloadable PDF report you can save, share with a mechanic, or use as a negotiation document with the seller.",
  },
];

export default function FAQ() {
  const [openIdx, setOpenIdx] = useState<number | null>(null);

  return (
    <section id="faq" className="py-24 bg-[#070d1a]">
      <div className="max-w-3xl mx-auto px-4 sm:px-6">
        <div className="text-center mb-12">
          <span className="inline-block px-3 py-1 bg-slate-500/10 border border-slate-500/30 rounded-full text-slate-400 text-xs font-medium mb-4">
            FAQ
          </span>
          <h2 className="text-3xl sm:text-4xl font-bold text-white mb-4">
            Frequently Asked Questions
          </h2>
        </div>

        <div className="flex flex-col gap-3">
          {faqs.map((faq, i) => (
            <div
              key={i}
              className="bg-[#0f1c35] border border-white/8 rounded-xl overflow-hidden"
            >
              <button
                className="w-full flex items-center justify-between gap-4 px-6 py-4 text-left"
                onClick={() => setOpenIdx(openIdx === i ? null : i)}
              >
                <span className="text-sm font-medium text-white">{faq.q}</span>
                <span
                  className={`text-slate-400 transition-transform flex-shrink-0 ${
                    openIdx === i ? "rotate-180" : ""
                  }`}
                >
                  <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                    <path
                      d="M4 6l4 4 4-4"
                      stroke="currentColor"
                      strokeWidth="1.5"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                  </svg>
                </span>
              </button>
              {openIdx === i && (
                <div className="px-6 pb-4 text-sm text-slate-400 leading-relaxed border-t border-white/5 pt-4">
                  {faq.a}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
